### ISSUE TITLE
Declaration not compatible with RabbitMQJob::delete

### ISSUE THREAD

**Issue by ibrunotome** [designmynight/laravel-horizon-rabbitmq#12]
Hi, just send the first job to a rabbitmq queue and get this:

`Symfony\Component\Debug\Exception\FatalErrorException  : Declaration of DesignMyNight\Laravel\Horizon\Jobs\RabbitMQJob::delete() must be compatible with VladimirYuldashev\LaravelQueueRabbitMQ\Queue\Jobs\RabbitMQJob::delete(): void
`

**Comment by wbgneto** [comment]
Please accept https://github.com/designmynight/laravel-horizon-rabbitmq/pull/11

**Comment by StevePorter92** [comment]
Thank you both @ibrunotome @wbgneto
