### ISSUE TITLE
Version for lumen

### ISSUE THREAD

**Issue by iocaste** [designmynight/laravel-horizon-rabbitmq#9]
Package works with lumen, but only if composer.json dep "laravel/horizon": "^1.4", is changed from official horizon to "kinsolee/horizon-lumen": "^1.2" (It is port for lumen)

Is there possibility to make this package also ready for lumen ? Or should I create separate package called "lumen-horizon-rabbitmq" ?

**Comment by StevePorter92** [comment]
It doesn’t look like the kinsolee/horizon-lumen is versioned against the official horizon package. I think the best option here is for you to create a lumen-horizon-rabbitmq fork so this package remains being safely versioned against the official laravel framework and laravel horizon packages.
